# Generated by Django 6.0.5 on 2026-05-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='conductores.conductor')),
            ],
        ),
    ]
